name: meep
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pymeep
  - pymeep-extras
  - pytorch>=2.3
  - stable-baselines3
  - gymnasium
  - numpy
  - scipy
  - matplotlib-base
  - pandas
  - tensorboard
